In [1]:
import pandas as pd
import numpy as np

In [5]:
UOS_ROUTE =['NEPCB','UOSCB','UOSCO','UOSGW','CMDCB','CMDGW','CUMCB','CUMGW','NEPGW']
PATH = 'D:\\Run Analysis\\BLOB_STORAGE\\tipping_weekly\\waste_edge_tipping\\17th_2021.csv'
df = pd.read_csv(PATH)
df[['Route No', 'Weekday']]= df['Route No'].str.split('-', 1, expand=True)
df['Route Date'] = pd.to_datetime(df['Route Date'], format='%d-%b-%Y', errors='coerce')
df['Disposal Date'] = pd.to_datetime(df['Disposal Date'], format='%d-%b-%Y', errors='coerce')
df['Tip Site'] = df['Tip Site'].str.lower()

df_a = df[df['Route No'].isin(UOS_ROUTE)]

In [7]:
df_a = df_a.loc[~(df_a['Gross Weight'] > 0 ) & ~(df_a['Tare Weight'] > 0 )]

In [8]:
d

,Sequence No,Booking No,Customer Details,Route No,Truck No,Route Date,Disposal Date,Tip Site,Tip In Time,Tip Out Time,...,Charge Rate,Total Charge,Waste Type,Weight,UOM,Docket No,Gross Weight,Tare Weight,Branch,Weekday
3,232031393,2732308.0,4043.076 - Cumberland Campus - Building C43L,CUMGW,CQ64LO,2021-04-28,2021-04-28,NaN,NaN,NaN,...,0.0,0.0,GW,30.0,TONNES,NaN,0.0,0.0,Sydney Waste,3
128,232034197,2733502.1,4043.029 - F03 Fisher Library,UOSGW,XN76VB,2021-04-28,2021-04-28,NaN,NaN,NaN,...,0.0,0.0,GW,86.0,TONNES,NaN,0.0,0.0,NaN,3
129,232034208,2733502.2,4043.029 - F03 Fisher Library,UOSGW,XN76VB,2021-04-28,2021-04-28,NaN,NaN,NaN,...,0.0,0.0,GW,102.0,Kg,NaN,0.0,0.0,NaN,3
130,232034198,2733503.0,"4043.03 - A14 The Quadrangle, A18 Brennan McCa...",UOSGW,XN76VB,2021-04-28,2021-04-28,NaN,NaN,NaN,...,0.0,0.0,GW,66.0,TONNES,NaN,0.0,0.0,NaN,3
131,232034251,2733503.2,"4043.03 - A14 The Quadrangle, A18 Brennan McCa...",UOSGW,XN76VB,2021-04-28,2021-04-28,NaN,NaN,NaN,...,0.0,0.0,GW,58.0,Kg,NaN,0.0,0.0,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,237268932,2740390.0,4043.055 - K07 Margaret Telfer,UOSGW,XN76VB,2021-05-04,2021-05-04,NaN,NaN,NaN,...,0.0,0.0,GW,24.0,TONNES,NaN,0.0,0.0,NaN,2
1191,237268934,2740392.0,4043.057 - K25 Medical Foundation,UOSGW,XN76VB,2021-05-04,2021-05-04,NaN,NaN,NaN,...,0.0,0.0,GW,48.0,Kg,NaN,0.0,0.0,NaN,2
1192,237268935,2740393.0,4043.058 - K06 1-3 Ross St,UOSGW,XN76VB,2021-05-04,2021-05-04,NaN,NaN,NaN,...,0.0,0.0,GW,66.0,Kg,NaN,0.0,0.0,NaN,2
1193,237268937,2740395.0,4043.083 - D18 Susan Wakil Health Building,UOSGW,XN76VB,2021-05-04,2021-05-04,NaN,NaN,NaN,...,0.0,0.0,GW,64.0,TONNES,NaN,0.0,0.0,NaN,2
1194,237268938,2740395.1,4043.083 - D18 Susan Wakil Health Building,UOSGW,XN76VB,2021-05-04,2021-05-04,NaN,NaN,NaN,...,0.0,0.0,GW,2.0,TONNES,NaN,0.0,0.0,NaN,2