In [8]:
import pandas as pd
import numpy as np

In [9]:
PATH17 = 'D:\\Run Analysis\\BLOB_STORAGE\\tipping_weekly\\waste_edge_tipping\\17th_2021.csv'
PATH18 = 'D:\\Run Analysis\\BLOB_STORAGE\\tipping_weekly\\waste_edge_tipping\\18th_2021.csv'

df_17 = pd.read_csv(PATH17)
df_18 = pd.read_csv(PATH18)

# Clean Route , transform date
df_17[['Route No', 'Weekday']]= df_17['Route No'].str.split('-', 1, expand=True)
df_17['Route Date'] = pd.to_datetime(df_17['Route Date'], format='%d-%b-%Y', errors='coerce')
df_17['Disposal Date'] = pd.to_datetime(df_17['Disposal Date'], format='%d-%b-%Y', errors='coerce')

In [20]:
# UOS
UOS_ROUTE =['NEPCB','UOSCB','UOSCO','UOSGW','CMDCB','CMDGW','CUMCB','CUMGW','NEPGW']
# df_17_uos = df_17
df_17_uos = df_17[df_17['Route No'].isin(UOS_ROUTE)

In [ ]:
df_general_tip = df_17[(df_17['Gross Weight'] > 0) & (df_17['Tare Weight'] > 0)]

In [43]:
# Display the Catgories
# After knowing the tip categories
df_general_tip['Waste Type'].unique()

array(['PC', 'CO', 'CB', 'GW', nan], dtype=object)

In [55]:
# filter by 
cb = ['FLP','HYG','RED','RL5','RL6','RL8','RLP','RLR'] 
df_cb = df_general_tip[df_general_tip['Waste Type'].eq('CB')]
df_cb[~df_cb['Route No'].isin(cb)]['Route No'].values
df_cb['Tip Site']
# .groupby('Route No')['Weight'].sum()

,Sequence No,Booking No,Customer Details,Route No,Truck No,Route Date,Disposal Date,Tip Site,Tip In Time,Tip Out Time,...,Charge Rate,Total Charge,Waste Type,Weight,UOM,Docket No,Gross Weight,Tare Weight,Branch,Weekday
192,234388949,0.0,NaN,RL8,XN62UD,2021-04-28,2021-04-29,Grima Recycling,NaN,01:01:33,...,110.0,0.0,CB,1.48,TONNES,255017,9.30,7.82,NaN,3
193,234399373,0.0,NaN,RLR,CG94KY,2021-04-28,2021-04-29,Grima Recycling,NaN,03:35:37,...,110.0,0.0,CB,2.14,TONNES,255022,9.98,7.84,NaN,3
194,234399854,0.0,NaN,RL8,XN62UD,2021-04-28,2021-04-29,Grima Recycling,NaN,04:06:31,...,110.0,0.0,CB,1.40,TONNES,255026,9.22,7.82,NaN,3
196,234399374,0.0,NaN,RED,CG06UT,2021-04-28,2021-04-29,Grima Recycling,NaN,03:36:09,...,110.0,0.0,CB,1.16,TONNES,W-255024,11.84,10.68,NaN,3
197,233573658,0.0,NaN,HYG,CF48ED,2021-04-28,2021-04-28,Grima Recycling,NaN,12:10:36,...,110.0,0.0,CB,2.00,TONNES,W254975,12.26,10.26,NaN,3
225,233571640,0.0,NaN,HOOKCB,XN23UV,2021-04-28,2021-04-28,OATLEY RESOURCES,NaN,10:07:04,...,135.0,0.0,CB,2.46,TONNES,20001000093172,19.32,16.86,NaN,3
423,235535453,0.0,NaN,RLR,CG94KY,2021-04-29,2021-04-30,Grima Recycling,NaN,04:02:20,...,110.0,0.0,CB,1.94,TONNES,255110,9.78,7.84,NaN,4
424,235535346,0.0,NaN,RL8,XN62UD,2021-04-29,2021-04-30,Grima Recycling,3:17,3:26,...,110.0,0.0,CB,2.28,TONNES,w-255122,12.78,10.50,NaN,4
426,234934982,0.0,NaN,HYG,CF48ED,2021-04-29,2021-04-29,Grima Recycling,NaN,11:13:09,...,110.0,0.0,CB,1.24,TONNES,W255074,11.50,10.26,NaN,4
666,236541466,0.0,NaN,RLR,CG94KY,2021-04-30,2021-05-01,Grima Recycling,NaN,05:14:00,...,110.0,0.0,CB,1.08,TONNES,255217,7.92,6.84,NaN,5
670,235952382,0.0,NaN,HYG,CF48ED,2021-04-30,2021-04-30,Grima Recycling,NaN,11:07:36,...,110.0,0.0,CB,1.80,TONNES,W255177,12.06,10.26,NaN,5
989,238599918,0.0,NaN,RED,CG06UT,2021-05-03,2021-05-04,Grima Recycling,NaN,02:28:04,...,110.0,0.0,CB,2.04,TONNES,+,12.72,10.68,NaN,1
990,238412439,0.0,NaN,RLR,CG94KY,2021-05-03,2021-05-04,Grima Recycling,NaN,00:03:12,...,110.0,0.0,CB,1.24,TONNES,255336,8.08,6.84,NaN,1
991,238599974,0.0,NaN,RL8,XN62UD,2021-05-03,2021-05-04,Grima Recycling,NaN,03:13:28,...,110.0,0.0,CB,2.92,TONNES,255342,13.42,10.50,NaN,1
992,238011854,0.0,NaN,HYG,CF48ED,2021-05-03,2021-05-03,Grima Recycling,NaN,13:35:22,...,110.0,0.0,CB,2.76,TONNES,W255307,13.02,10.26,NaN,1
1212,239851290,0.0,NaN,RLR,CG94KY,2021-05-04,2021-05-05,Grima Recycling,NaN,04:27:12,...,110.0,0.0,CB,2.00,TONNES,255459,9.84,7.84,NaN,2
1213,239851055,0.0,NaN,RL8,XN62UD,2021-05-04,2021-05-05,Grima Recycling,NaN,02:53:51,...,110.0,0.0,CB,2.24,TONNES,255463,12.74,10.50,NaN,2
1214,239052869,0.0,NaN,HYG,CF48ED,2021-05-04,2021-05-04,Grima Recycling,NaN,08:56:06,...,110.0,0.0,CB,1.14,TONNES,W255388,11.40,10.26,NaN,2
1215,239257287,0.0,NaN,UOSCB,CQ64LO,2021-05-04,2021-05-04,Grima Recycling,NaN,12:33:58,...,110.0,0.0,CB,0.90,TONNES,W255408,8.84,7.94,NaN,2

In [47]:
df_17_uos

,Sequence No,Booking No,Customer Details,Route No,Truck No,Route Date,Disposal Date,Tip Site,Tip In Time,Tip Out Time,...,Charge Rate,Total Charge,Waste Type,Weight,UOM,Docket No,Gross Weight,Tare Weight,Branch,Weekday
3,232031393,2732308.0,4043.076 - Cumberland Campus - Building C43L,CUMGW,CQ64LO,2021-04-28,2021-04-28,NaN,NaN,NaN,...,0.0,0.0,GW,30.00,TONNES,NaN,0.00,0.00,Sydney Waste,3
128,232034197,2733502.1,4043.029 - F03 Fisher Library,UOSGW,XN76VB,2021-04-28,2021-04-28,NaN,NaN,NaN,...,0.0,0.0,GW,86.00,TONNES,NaN,0.00,0.00,NaN,3
129,232034208,2733502.2,4043.029 - F03 Fisher Library,UOSGW,XN76VB,2021-04-28,2021-04-28,NaN,NaN,NaN,...,0.0,0.0,GW,102.00,Kg,NaN,0.00,0.00,NaN,3
130,232034198,2733503.0,"4043.03 - A14 The Quadrangle, A18 Brennan McCa...",UOSGW,XN76VB,2021-04-28,2021-04-28,NaN,NaN,NaN,...,0.0,0.0,GW,66.00,TONNES,NaN,0.00,0.00,NaN,3
131,232034251,2733503.2,"4043.03 - A14 The Quadrangle, A18 Brennan McCa...",UOSGW,XN76VB,2021-04-28,2021-04-28,NaN,NaN,NaN,...,0.0,0.0,GW,58.00,Kg,NaN,0.00,0.00,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,237268935,2740393.0,4043.058 - K06 1-3 Ross St,UOSGW,XN76VB,2021-05-04,2021-05-04,NaN,NaN,NaN,...,0.0,0.0,GW,66.00,Kg,NaN,0.00,0.00,NaN,2
1193,237268937,2740395.0,4043.083 - D18 Susan Wakil Health Building,UOSGW,XN76VB,2021-05-04,2021-05-04,NaN,NaN,NaN,...,0.0,0.0,GW,64.00,TONNES,NaN,0.00,0.00,NaN,2
1194,237268938,2740395.1,4043.083 - D18 Susan Wakil Health Building,UOSGW,XN76VB,2021-05-04,2021-05-04,NaN,NaN,NaN,...,0.0,0.0,GW,2.00,TONNES,NaN,0.00,0.00,NaN,2
1215,239257287,0.0,NaN,UOSCB,CQ64LO,2021-05-04,2021-05-04,Grima Recycling,NaN,12:33:58,...,110.0,0.0,CB,0.90,TONNES,W255408,8.84,7.94,NaN,2
1218,239257248,0.0,NaN,UOSGW,XN76VB,2021-05-04,2021-05-04,Suez - Auburn,NaN,12:31:17,...,1.0,0.0,GW,2.94,TONNES,AU120116662,13.96,11.02,NaN,2

In [4]:
df_17['Tip Site']

NameError: name 'df_17' is not defined