In [1]:
import pandas as pd
import numpy as np

In [8]:
PATH = 'D:\\Run Analysis\\BLOB_STORAGE\\expenses_truck\\all_other_mv_expense\\to_be_process\\20th_2021.xlsx'          
df = pd.read_excel(PATH)

df.Date = pd.to_datetime(df.Date, format='%d/%m/%Y')

COMPLETE_PATH = 'D:\\Run Analysis\\BLOB_STORAGE\\expenses_truck\\all_other_mv_expense\\to_be_process\\20th_2021_.xlsx'          
df[df.Date.between('20210519', '20210525')].to_excel(COMPLETE_PATH)

,catID,cat,Date,Memo,Debit,Job No.
0,OTHER,OTHER,2021-05-31,Purchase; SUPAGAS,312.00,FLEET
1,CC,MV R&M - Cab&Chassic,2021-05-19,Purchase; MULTISPARES,53.13,CV50EC
2,CC,MV R&M - Cab&Chassic,2021-05-20,Purchase; MULTISPARES,129.63,XN62UD
3,CC,MV R&M - Cab&Chassic,2021-05-25,Purchase; Tony Perino Engineering Pty Ltd,456.00,New Truck
4,CC,MV R&M - Cab&Chassic,2021-05-25,Purchase; Tony Perino Engineering Pty Ltd,110.00,XN71FD
5,CC,MV R&M - Cab&Chassic,2021-05-26,Purchase; T.M.Elite Automatics,500.00,XN75OS
6,CC,MV R&M - Cab&Chassic,2021-05-26,Purchase; T.M.Elite Automatics,534.20,New Truck
7,CC,MV R&M - Cab&Chassic,2021-05-26,Purchase; T.M.Elite Automatics,534.20,New Front Lift
8,CC,MV R&M - Cab&Chassic,2021-05-27,Purchase; MULTISPARES,736.88,CQ64LO
9,CC,MV R&M - Cab&Chassic,2021-05-28,Purchase; MULTISPARES,809.36,New Skip Bin Truck
10,CC,MV R&M - Cab&Chassic,2021-05-29,Purchase; Gazza's Paint & Panel,4500.00,New Truck
11,CC,MV R&M - Cab&Chassic,2021-05-29,Purchase; Buddy Motor Trimming,200.00,CQ64LO
12,CC,MV R&M - Cab&Chassic,2021-05-31,Purchase; MULTISPARES,165.97,CG94KY
13,CB,MV R&M - Compactor/Body,2021-05-24,Purchase; Penblack Pty Ltd RYCO 24/7 Penrith,312.83,XN10HU
14,CB,MV R&M - Compactor/Body,2021-05-25,Purchase; Tony Perino Engineering Pty Ltd,144.00,New Truck
15,CB,MV R&M - Compactor/Body,2021-05-25,Purchase; Tony Perino Engineering Pty Ltd,80.00,XPL658
16,CB,MV R&M - Compactor/Body,2021-05-25,Purchase; Tony Perino Engineering Pty Ltd,3800.00,CN41XN
17,CB,MV R&M - Compactor/Body,2021-05-31,Purchase; Austlift Pty Ltd,5850.00,DA59TU
18,CB,MV R&M - Compactor/Body,2021-05-31,Purchase; Pirtek Smithfield Pty Ltd,131.48,XN80YD
19,CB,MV R&M - Compactor/Body,2021-06-01,Purchase; Tony Perino Engineering Pty Ltd,711.00,XN25GD
20,CB,MV R&M - Compactor/Body,2021-06-01,Purchase; Tony Perino Engineering Pty Ltd,391.00,CN41XN
21,CB,MV R&M - Compactor/Body,2021-06-01,Purchase; Tony Perino Engineering Pty Ltd,217.00,New Front Lift
22,CB,MV R&M - Compactor/Body,2021-06-01,Purchase; Penblack Pty Ltd RYCO 24/7 Penrith,250.95,XN75OS
23,MC,MV R&M - Misc Consum,2021-05-20,Purchase; Cedray,29.58,FLEET
24,MC,MV R&M - Misc Consum,2021-06-01,Purchase; Tony Perino Engineering Pty Ltd,345.00,FLEET
25,LABOUR,MV Workshop Contractor Labour,2021-05-25,Purchase; Tony Perino Engineering Pty Ltd,1560.00,FLEET
26,LABOUR,MV Workshop Contractor Labour,2021-05-25,Purchase; Tony Perino Engineering Pty Ltd,2520.00,FLEET
27,LABOUR,MV Workshop Contractor Labour,2021-05-25,Purchase; Tony Perino Engineering Pty Ltd,900.00,FLEET
28,LABOUR,MV Workshop Contractor Labour,2021-05-25,Purchase; Tony Perino Engineering Pty Ltd,1000.00,FLEET
29,LABOUR,MV Workshop Contractor Labour,2021-05-25,Purchase; Tony Perino Engineering Pty Ltd,1125.00,FLEET
30,LABOUR,MV Workshop Contractor Labour,2021-05-31,Purchase; Tony Perino Engineering Pty Ltd,1380.00,FLEET
31,LABOUR,MV Workshop Contractor Labour,2021-05-31,Purchase; Tony Perino Engineering Pty Ltd,2400.00,FLEET
32,LABOUR,MV Workshop Contractor Labour,2021-05-31,Purchase; Tony Perino Engineering Pty Ltd,1440.00,FLEET
33,LABOUR,MV Workshop Contractor Labour,2021-05-31,Purchase; Tony Perino Engineering Pty Ltd,1000.00,FLEET

In [3]:
PATH_MVEXP = 'D:\\Run Analysis\\BLOB_STORAGE\\expenses_truck\\all_other_mv_expense\\to_be_process\\17th_2021.xlsx'
PATH_ROS = 'D:\\Run Analysis\\BLOB_STORAGE\\Roster\\weekly_roster_processed\\17th_2021.xlsx'
PATH_OLDROS = 'D:\\Run Analysis\\BLOB_STORAGE\\Roster\\Rearranged_past_roster\\All_Past_Sorted_ROSTER.csv'

df_mvexp = pd.read_excel(PATH_MVEXP)
df_ros = pd.read_excel(PATH_ROS)

df_mvexp.iloc[:,3] = pd.to_datetime(df_mvexp.iloc[:,3], format="%d/%m/%Y")
df_mvexp

,catID,cat,ID No.,Date,Memo,Debit,Credit,Job No.
0,CC,MV R&M - Cab&Chassic,4154238,2021-04-28,Purchase; MULTISPARES,105.52,NaN,XN62UD
1,CC,MV R&M - Cab&Chassic,4154240,2021-04-28,Purchase; CITY HINO as IVECO Sydney,148.91,NaN,XN06OJ
2,CC,MV R&M - Cab&Chassic,4154241,2021-04-28,Purchase; CITY HINO as IVECO Sydney,131.52,NaN,CF48ED
3,CC,MV R&M - Cab&Chassic,4154244,2021-04-28,Purchase; CITY HINO as IVECO Sydney,501.03,NaN,XN13KR
4,CC,MV R&M - Cab&Chassic,4154247,2021-04-28,Purchase; MULTISPARES,31.27,NaN,XN71FD
5,CC,MV R&M - Cab&Chassic,4154250,2021-04-28,Purchase; CITY HINO as IVECO Sydney,162.67,NaN,CJ65PS
6,CC,MV R&M - Cab&Chassic,4154239,2021-04-29,Purchase; CITY HINO as IVECO Sydney,62.74,NaN,XN06OJ
7,CC,MV R&M - Cab&Chassic,4154243,2021-04-29,Purchase; CITY HINO as IVECO Sydney,63.77,NaN,CF48ED
8,CC,MV R&M - Cab&Chassic,4154284,2021-04-29,Purchase; MULTISPARES,135.00,NaN,XN80YD
9,CC,MV R&M - Cab&Chassic,4154285,2021-04-29,Purchase; MULTISPARES,375.68,NaN,XN62UD
10,CC,MV R&M - Cab&Chassic,4154286,2021-04-29,Purchase; MULTISPARES,69.18,NaN,XN62UD
11,CC,MV R&M - Cab&Chassic,4154178,2021-04-30,Purchase; D J Burnes and L G Automotive,180.00,NaN,CMA32H
12,CC,MV R&M - Cab&Chassic,4154242,2021-04-30,Purchase; CITY HINO as IVECO Sydney,38.00,NaN,CF48ED
13,CC,MV R&M - Cab&Chassic,4154222,2021-05-02,Purchase; Tony Perino Engineering Pty Ltd,120.00,NaN,CQ64LO
14,CC,MV R&M - Cab&Chassic,4154222,2021-05-02,Purchase; Tony Perino Engineering Pty Ltd,240.00,NaN,XN10HU
15,CC,MV R&M - Cab&Chassic,4154222,2021-05-02,Purchase; Tony Perino Engineering Pty Ltd,120.00,NaN,CL02TB
16,CB,MV R&M - Compactor/Body,4154282,2021-04-28,Purchase; Pirtek Smithfield Pty Ltd,232.57,NaN,CJ65PS
17,CB,MV R&M - Compactor/Body,4154176,2021-04-29,Purchase; TSM SIGNS Total Sign Management,175.00,NaN,FLEET
18,CB,MV R&M - Compactor/Body,4154176,2021-04-29,Purchase; TSM SIGNS Total Sign Management,175.00,NaN,XN49YC
19,CB,MV R&M - Compactor/Body,4154176,2021-04-29,Purchase; TSM SIGNS Total Sign Management,175.00,NaN,CF71JM
20,CB,MV R&M - Compactor/Body,4154176,2021-04-29,Purchase; TSM SIGNS Total Sign Management,175.00,NaN,XN80YD
21,CB,MV R&M - Compactor/Body,4154176,2021-04-29,Purchase; TSM SIGNS Total Sign Management,50.00,NaN,XN62UD
22,CB,MV R&M - Compactor/Body,4154223,2021-05-02,Purchase; Tony Perino Engineering Pty Ltd,240.00,NaN,XN65IJ
23,MC,MV R&M - Misc Consum,4154277,2021-04-28,Purchase; OMEGA Industries,335.00,NaN,FLEET
24,TYRES,M.V R&M - Tyres,4154249,2021-04-29,Purchase; West City Tyres Pty Ltd,245.00,NaN,XN81VB
25,TYRES,M.V R&M - Tyres,4154278,2021-04-29,Purchase; West City Tyres Pty Ltd,630.00,NaN,CL02TB
26,TYRES,M.V R&M - Tyres,4154280,2021-04-29,Purchase; West City Tyres Pty Ltd,60.00,NaN,XN10HU
27,LABOUR,MV Workshop Contractor Labour,4154216,2021-05-02,Purchase; Tony Perino Engineering Pty Ltd,1000.00,NaN,FLEET
28,LABOUR,MV Workshop Contractor Labour,4154217,2021-05-02,Purchase; Tony Perino Engineering Pty Ltd,2400.00,NaN,FLEET
29,LABOUR,MV Workshop Contractor Labour,4154218,2021-05-02,Purchase; Tony Perino Engineering Pty Ltd,1000.00,NaN,FLEET
30,OTHER2,Fines & Penalties,4154179,2021-04-30,Purchase; Office of State Revenue,272.00,NaN,DZU72Z

In [21]:
# df_mvexp.groupby('catID')['Debit'].sum()
# df_mvexp
# df.groupby(['Job No.','catID'])['Debit'].sum()

df_ros.Primary_truck = df_ros.Primary_truck.str.replace(' ','')
df_ros

,Date,Run_type,Primary_employeeID,Secondary_employeeID,Primary_driver_Name,Secondary_Driver_Name,Primary_route,Satellite_Route_1,Satellite_Route_2,Primary_truck,Alternative_Truck,Subcontracted_From/Special_Client
0,2021-04-28,NIGHT RUNS,swaklado,NaN,ADONIS AKL,NaN,RLE,NaN,NaN,CL98LU,NaN,NaN
1,2021-04-29,NIGHT RUNS,swaklado,NaN,ADONIS AKL,NaN,RLE,NaN,NaN,CL98LU,NaN,NaN
2,2021-04-30,NIGHT RUNS,swaklado,NaN,ADONIS AKL,NaN,RLE,NaN,NaN,CL98LU,NaN,NaN
3,2021-05-03,NIGHT RUNS,swaklado,NaN,ADONIS AKL,NaN,RLE,NaN,NaN,CL98LU,NaN,NaN
4,2021-05-04,NIGHT RUNS,swaklado,NaN,ADONIS AKL,NaN,RLE,NaN,NaN,CL02TB,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
132,2021-04-28,DAY RUNS,irdeaz,NaN,ZAC DEAN,NaN,RL7,NaN,NaN,XN44QZ,NaN,NaN
133,2021-04-29,DAY RUNS,irdeaz,NaN,ZAC DEAN,NaN,RL7,NaN,NaN,XN44QZ,NaN,NaN
134,2021-04-30,DAY RUNS,irdeaz,NaN,ZAC DEAN,NaN,RL7,NaN,NaN,XN44QZ,NaN,NaN
135,2021-05-01,DAY RUNS,irdeaz,NaN,ZAC DEAN,NaN,RL7,NaN,NaN,XN44QZ,NaN,NaN
136,2021-05-04,DAY RUNS,irdeaz,NaN,ZAC DEAN,NaN,RL7,NaN,NaN,XN44QZ,NaN,NaN